### ISSUE TITLE
CSS 清楚浮动的8中方法

### ISSUE THREAD

**Issue by KuangPF** [KuangPF/FE-blog#3]
为什么清除CSS浮动这么难？
因为浮动会使当前标签产生向上浮的效果，同时会影响到前后标签、父级标签的位置及 width height 属性。
而且同样的代码，在各种浏览器中显示效果也有可能不相同，这样让清除浮动更难了。
解决浮动引起的问题有多种方法，但有些方法在浏览器兼容性方面还有问题。
我根据自己的经验总结8种清除浮动的方法（测试已通过 ie chrome firefox opera，后面三种方法只做了解就可以了）：
#### 1.父级 div 定义高度
```html
<div class="case1">
    <div class="title">1.父级div定义height</div>
	<div class="div1">
	    <div class="left"></div>
	    <div class="right"></div>
	</div>
    <div class="div2"></div>
</div>
```
```css
.case1 {
    .div1 {
	height: 100px;   // 解决代码
	margin-top: 10px;
      .left {
        float: left;
        width: 40%;
        height: 100px;
        background: #108ffb;
      }
      .right {
        float: right;
        width: 40%;
        height: 100px;
        background: #B70000;
      }
    }
    .div2 {
	height: 100px;
	margin-top: 10px;
	background-color: #326151;
    }
}
```
* 原理：父级div手动定义height，就解决了父级div无法自动获取到高度的问题
* 优点：简单,代码少，容易掌握
* 缺点：只适合高度固定的布局，要给出精确的高度，如果高度和父级div不一样时，会产生问题
* 建议：不推荐使用，只建议高度固定的布局时使用
* 评分：:star::star:
#### 2.结尾处加空div标签clear:both
```html
<div class="case2">
    <div class="title">2.结尾处加空div标签clear:both</div>
    <div class="div1">
        <div class="left"></div>
	<div class="right"></div>
    </div>
    <div class="div-clear"></div>
    <div class="div2"></div>
</div>
```
```css
.div-clear {
    clear:both;
}
```
* 原理：添加一个空div，利用css提供的clear:both清除浮动，让父级div能自动获取到高度
* 优点：简单，代码少，浏览器支持好，不容易出现怪问题
* 缺点：不少初学者不理解原理；如果页面浮动布局多，就要增加很多空div，让人感觉很不爽
* 建议：不推荐使用，但此方法是以前主要使用的一种清除浮动方法
* 评分：:star::star::star:
#### 3.父级div定义伪类:after和zoom
```html
<div class="case3">
    <div class="title">3.父级div定义伪类:after和zoom</div>
	<div class="div1 clearfix">
	    <div class="left"></div>
	    <div class="right"></div>
	</div>
    <div class="div2"></div>
</div>
```
```css
.clearfix {
    zoom:1
    &::after {
        content: '';
	display: block;
	height: 0;
	visibility: hidden;
	clear: both;
    }
}
```
* 原理：IE8以上和非IE浏览器才支持:after，原理和方法2有点类似，zoom(IE转有属性)可解决ie6,ie7浮动问题
* 优点：浏览器支持好，不容易出现怪问题（目前：大型网站都有使用，如：腾迅，网易，新浪等等）
* 缺点：代码多，不少初学者不理解原理，要两句代码结合使用，才能让主流浏览器都支持
* 建议：推荐使用，建议定义公共类，以减少CSS代码
* 评分：:star::star::star::star:
#### 4.父级div定义overflow:hidden
```html
<div class="case4">
    <div class="title">4.父级div定义overflow:hidden</div>
	<div class="div1">
	    <div class="left"></div>
	    <div class="right"></div>
	</div>
    <div class="div2"></div>
</div>
```
```css
.div1 {
    overflow:hidden;
}
```
* 原理：父级元素不能定义height，使用overflow:hidden时，浏览器会自动检查浮动区域的高度
* 优点：简单，代码少，浏览器支持好
* 缺点：不能和position配合使用，因为超出的尺寸的会被隐藏
* 建议：只推荐没有使用position或对overflow:hidden理解比较深的朋友使用
* 评分：:star::star::star:
#### 5.父级div定义overflow:auto
```html
<div class="case5">
    <div class="title">5.父级div定义overflow:auto</div>
	<div class="div1">
	    <div class="left"></div>
	    <div class="right"></div>
	</div>
    <div class="div2"></div>
</div>
```
```css
.div1 {
    overflow:auto;
}
```
* 原理：父级元素不能定义height，使用overflow:hidden时，浏览器会自动检查浮动区域的高度
* 优点：简单，代码少，浏览器支持好
* 缺点：内部宽高超过父级div时，会出现滚动条。
* 建议：不推荐使用，如果你需要出现滚动条或者确保你的代码不会出现滚动条就使用吧。
* 评分：:star::star:
#### 6.父级div也一起浮动
```html
<div class="case6">
    <div class="title">6.父级div也一起浮动</div>
	<div class="div1">
	    <div class="left"></div>
	    <div class="right"></div>
	</div>
    <div class="div2"></div>
</div>
```
```css
.div1 {
    float: left;
    width: 100%;
}
.div2 {
    clear:both
}
```
* 原理：所有代码一起浮动，就变成了一个整体,但父元素必须设定宽度
* 优点：没有优点
* 缺点：会产生新的浮动问题
* 建议：不推荐使用，只作了解。
* 评分：:star:
#### 7.父级div定义display:table
```html
<div class="case7">
    <div class="title">7.父级div定义display:table</div>
	<div class="div1">
	    <div class="left"></div>
	    <div class="right"></div>
	</div>
    <div class="div2"></div>
</div>
```
```css
.div1 {
    display: table;
    width: 100%;
}
```
* 原理：将div属性变成表格,父级元素需要设置 width
* 优点：没有优点
* 缺点：会产生新的浮动问题
* 建议：不推荐使用，只作了解。
* 评分：:star:
#### 8.结尾处加br标签clear:both
```html
<div class="case8">
    <div class="title">7.父级div定义display:table</div>
	<div class="div1">
	    <div class="left"></div>
	    <div class="right"></div>
            <br class="clear-br" />
	</div>
    <div class="div2"></div>
</div>
```
```css
.div1 {
    zoom: 1
}
.clear-br {
    clear: both;
}
```
* 原理：父级div定义zoom:1来解决IE浮动问题，结尾处加br标签clear:both
* 建议：不推荐使用，只作了解。
* 评分：:star:

## 总结
上面所罗列出的8种清除浮动方法，总结一下，常用的清除浮动就是父级div定义伪类:after和zoom，这种开发中很常见，可以少些很多css代码，而且兼容性很好。
[转载学习](https://www.cnblogs.com/AnotherLife/p/5800751.html)
